# Generated by Django 5.2.11 on 2026-03-05 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "students",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.students",
                    ),
                ),
            ],
        ),
    ]
